#!/bin/bash

STATUS=0
APL=/usr/bin/apl
APL_OPTS="--silent --Color"
cp --recursive exercises tmp

for exercise in tmp/*; do
  pushd $exercise
  for example in *-example.apl; do
    mv $example ${example/-example/}
  done
  if ! ${APL} ${APL_OPTS} -T *.tc; then
    STATUS=1
  fi
  popd
done

echo "Exiting with status ${STATUS}."
exit $STATUS